---
title: "Final Project:  Clustering Analysis"
author: "Katherine M. Prioli"
date: "December 05, 2019"
output:
  pdf_document: default
  html_document: default
geometry: margin = 0.5in
---


Descriptives for the dissimilarity matrix:

```{r dissim, echo = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 6}
dissim_mat <- vegdist(nhanes_unsup_mat, method = "gower")
summary(dissim_mat) %>% 
  round(digits = 2) %>% 
  tidy() %>% 
  setNames(., c("Min", "Q1", "Median", "Mean", "Q3", "Max")) %>% 
  kable(format = "markdown")
```

```{r agnes_diana, echo = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 6}
nhanes_agnes <- hclust(d = dissim_mat, method = "ward.D2")   # ward.D2 performs agglomerative per hclust documentation

nhanes_diana <- diana(x = (dissim_mat %>% as.matrix()), diss = TRUE, keep.diss = TRUE) %>% 
  as.hclust()
```

```{r agnes_dend, warning = FALSE, message = FALSE, echo = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5}
ggthemr("flat", spacing = 0.1)

unsup_labs_reord_ag <- unsup_labs[nhanes_agnes$order] %>%    # Reordering leaf labels
  str_sub(start = 1L, end = 1L) %>% 
  as_tibble() %>% 
  mutate(BMI_cat = case_when(   # Modifying leaf labels to show BMI category abbreviations
    value == "1" ~ "UW",        # Underweight
    value == "2" ~ "HW",        # Healthy weight
    value == "3" ~ "OW",        # Overweight
    value == "4" ~ "OB"         # Obese
  )) %>% 
  select(BMI_cat) %>% 
  as_tibble() %>% 
  mutate(x = row_number(),
         labcolor = case_when(   # Have decided not to use text labels but keeping this here in case I change my mind
           BMI_cat == "UW" ~ "#B0B000",         # Yellow
           BMI_cat == "HW" ~ "#008318",         # Green
           BMI_cat == "OW" ~ "#FF8D03",         # Orange
           BMI_cat == "OB" ~ "#FF0000"),        # Red
         leafcolor = case_when(
           BMI_cat == "UW" ~ "#FFFF00",         # Yellow
           BMI_cat == "HW" ~ "#008318",         # Green
           BMI_cat == "OW" ~ "#FF8D03",         # Orange
           BMI_cat == "OB" ~ "#FF0000")) %>%    # Red
  select(x, BMI_cat, labcolor, leafcolor)

ag_labcolors <- unsup_labs_reord_ag

agnes_dend <- nhanes_agnes %>% 
  as.dendrogram() %>% 
  set("leaves_pch", 20, col = ag_labcolors$leafcolor) %>% 
  set("leaves_col", ag_labcolors$leafcolor) %>% 
  set("branches_lwd", 0.5)

agnes_dend_ggd <- agnes_dend %>% 
  as.ggdend()

agnes_dend_gg <- ggplot(agnes_dend_ggd, labels = FALSE) +
  scale_y_reverse() +
  coord_polar(theta = "x") +
  theme(text = element_text(face = "bold"),
        axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(angle = 0)) +
  xlab("") +
  ylab("") #+
  #ggtitle("AGNES Dendrogram")
agnes_dend_gg

ggthemr("flat")
```

```{r diana_dend, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5}
ggthemr("flat", spacing = 0.1)

unsup_labs_reord_di <- unsup_labs[nhanes_diana$order] %>%    # Reordering leaf labels
  str_sub(start = 1L, end = 1L) %>% 
  as_tibble() %>% 
  mutate(BMI_cat = case_when(   # Modifying leaf labels to show BMI category abbreviations
    value == "1" ~ "UW",        # Underweight
    value == "2" ~ "HW",        # Healthy weight
    value == "3" ~ "OW",        # Overweight
    value == "4" ~ "OB"         # Obese
  )) %>% 
  select(BMI_cat) %>% 
  as_tibble() %>% 
  mutate(x = row_number(),
         labcolor = case_when(   # Have decided not to use text labels but keeping this here in case I change my mind
           BMI_cat == "UW" ~ "#B0B000",
           BMI_cat == "HW" ~ "#008318",
           BMI_cat == "OW" ~ "#FF8D03",
           BMI_cat == "OB" ~ "#FF0000"),
         leafcolor = case_when(
           BMI_cat == "UW" ~ "#FFFF00",
           BMI_cat == "HW" ~ "#008318",
           BMI_cat == "OW" ~ "#FF8D03",
           BMI_cat == "OB" ~ "#FF0000")) %>% 
  select(x, BMI_cat, labcolor, leafcolor)

di_labcolors <- unsup_labs_reord_di

diana_dend <- nhanes_diana %>% 
  as.dendrogram() %>% 
  set("leaves_pch", 20, col = di_labcolors$leafcolor) %>% 
  set("leaves_col", di_labcolors$leafcolor) %>% 
  set("branches_lwd", 0.5)

diana_dend_ggd <- diana_dend %>% 
  as.ggdend()

diana_dend_gg <- ggplot(diana_dend_ggd, labels = FALSE) +
  scale_y_reverse() +
  coord_polar(theta = "x") +
  theme(text = element_text(face = "bold"),
        axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(angle = 0)) +
  xlab("") +
  ylab("") #+
  #ggtitle("DIANA Dendrogram")
diana_dend_gg

ggthemr("flat")
```

<!-- ```{r load_clust_RData, echo = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 6} -->
<!-- load("data/clustering_stats.RData") -->
<!-- ``` -->

```{r clust_sizes, warning = FALSE, echo = FALSE, paged.print = FALSE, fig.width = 12, fig.height = 4}
maxheight = rbind(agnes_sizes$cluster_size, diana_sizes$cluster_size) %>% 
  max()
ymax = ceiling(maxheight / 5) * 5

agnes_clustsize <- ggplot(data = agnes_sizes, aes(x = cluster_no, y = cluster_size)) +
  geom_col() +
  scale_x_continuous(breaks = c(0:15)) +
  ylim(0, ymax) +
  xlab("Cluster Number") +
  ylab("Cluster Size") +
  ggtitle("AGNES")

agnes_sizedesc <- summary(agnes_sizes$cluster_size) %>% 
  round(digits = 2) %>% 
  tidy() %>% 
  setNames(., c("Min", "Q1", "Median", "Mean", "Q3", "Max")) %>% 
  t() %>% 
  tableGrob(theme = ttheme_minimal(base_size = 10, padding = unit(c(2, 2), "mm")))

diana_clustsize <- ggplot(data = diana_sizes, aes(x = cluster_no, y = cluster_size)) +
  geom_col() +
  scale_x_continuous(breaks = c(0:15)) +
  ylim(0, ymax) +
  xlab("Cluster Number") +
  ylab("Cluster Size") +
  ggtitle("DIANA")

diana_sizedesc <- summary(diana_sizes$cluster_size) %>% 
  round(digits = 2) %>% 
  tidy() %>% 
  setNames(., c("Min", "Q1", "Median", "Mean", "Q3", "Max")) %>% 
  t() %>% 
  tableGrob(theme = ttheme_minimal(base_size = 10, padding = unit(c(2, 2), "mm")))

grid.arrange(agnes_sizedesc, agnes_clustsize, textGrob(" "), diana_sizedesc, diana_clustsize, 
             nrow = 1, ncol = 5, widths = c(0.25, 0.7, 0.1, 0.25, 0.7),
             top = textGrob("Cluster Sizes, k = 15 Clusters, Hierarchical Clustering Analysis",
                            gp = gpar(fontsize = 16, fontface = "bold", col = "#34495E"),
                            x = 0.025, hjust = 0))
```

```{r scree, echo = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 4}
agnes_scree <- ggplot(data = agnes_statdata, aes(x = n_clusters, y = withinss)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(0:15)) +
  xlab("Number of Clusters") +
  ylab("Within-Cluster Sum of Squares") +
  ggtitle("AGNES")

diana_scree <- ggplot(data = diana_statdata, aes(x = n_clusters, y = withinss)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(0:15)) +
  xlab("Number of Clusters") +
  ylab("Within-Cluster Sum of Squares") +
  ggtitle("DIANA")

screes <- grid.arrange(agnes_scree, diana_scree, nrow = 1,
                       top = textGrob("Scree Plots",
                                      gp = gpar(fontsize = 16, fontface = "bold", col = "#34495E"),
                                      x = 0.025, hjust = 0))
screes
```

```{r silhou, echo = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 4}
agnes_sil <- ggplot(data = agnes_statdata, aes(x = n_clusters, y = asw)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(0:15)) +
  xlab("Number of Clusters") +
  ylab("Average Silhouette Width") +
  ggtitle("AGNES")

diana_sil <- ggplot(data = diana_statdata, aes(x = n_clusters, y = asw)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(0:15)) +
  xlab("Number of Clusters") +
  ylab("Average Silhouette Width") +
  ggtitle("DIANA")

sils <- grid.arrange(agnes_sil, diana_sil, nrow = 1,
                     top = textGrob("Silhouette Plots",
                                    gp = gpar(fontsize = 16, fontface = "bold", col = "#34495E"),
                                    x = 0.025, hjust = 0))
sils
```

```{r leaves_segs, include = FALSE, echo = FALSE}
cluster_clusts <- function(df){
  leaves <- df$nodes %>% 
    filter(leaf == TRUE) %>% 
    select(x, col) %>% 
    rename(BMI_cat = col) %>% 
    mutate(BMI_cat = case_when(
      BMI_cat == "#FFFF00" ~ "Underweight",
      BMI_cat == "#008318" ~ "Healthy Weight",
      BMI_cat == "#FF8D03" ~ "Overweight",
      BMI_cat == "#FF0000" ~ "Obese"
    )) %>% 
    mutate(BMI_cat = factor(BMI_cat, levels = c("Underweight", "Healthy Weight", "Overweight", "Obese")))
  
  segs <- df$segments %>% 
    filter(yend == 0) %>% 
    select(x, col) %>% 
    rename(cluster_col = col)
  
  clusts <- leaves %>% 
    full_join(segs, by = "x") %>% 
    mutate(cluster_num = group_indices(., factor(cluster_col, levels = unique(cluster_col)))) %>%   # Numbering clusters
    group_by(cluster_num) %>%
    mutate(n_in_clust = n()) %>% 
    group_by(cluster_num, BMI_cat) %>% 
    mutate(n_cat_in_clust = n()) %>% 
    ungroup()
  
  clusts
}
```

```{r cluster_num_labs}
cluster_labs <- function(df){
  clust_labs <- cluster_clusts(df) %>% 
    mutate(cluster_num = paste0("Cluster #", cluster_num)) %>% 
    group_by(cluster_num) %>% 
    mutate(x_lab = mean(x)) %>%
    ungroup() %>% 
    select(x_lab, cluster_num, cluster_col) %>% 
    unique()
  
  clust_labs
}
```

```{r cluster_pct, include = FALSE, echo = FALSE}
cluster_pct <- function(df){
  
  clusts <- cluster_clusts(df) %>% 
    select(cluster_num, BMI_cat, n_in_clust, n_cat_in_clust) %>% 
    unique() %>% 
    arrange(cluster_num, BMI_cat) %>% 
    mutate(pct_cat_in_clust = round((n_cat_in_clust / n_in_clust) * 100, digits = 1),
           n_pct = paste0(n_cat_in_clust, " (", pct_cat_in_clust, "%)"),
           BMI_cat = paste0(BMI_cat, " (n, %)"),
           BMI_cat = factor(BMI_cat, levels = c("Underweight (n, %)",
                                                "Healthy Weight (n, %)",
                                                "Overweight (n, %)",
                                                "Obese (n, %)"))) %>% 
    select(cluster_num, BMI_cat, n_pct) %>% 
    spread(BMI_cat, n_pct, fill = "0 (0%)")
  
  clusts_kbl <- clusts %>%
    rename(Cluster = cluster_num) %>%
    kable(format = "markdown")

  clusts_kbl
}
```

```{r agnes_dend_clust_ggd_init, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5}
# 7 clusters for AGNES
agnes_dend_clust_init <- nhanes_agnes %>% 
  as.dendrogram() %>% 
  set("leaves_pch", 20, col = ag_labcolors$leafcolor) %>% 
  set("leaves_col", ag_labcolors$leafcolor) %>% 
  set("branches_lwd", 0.5) %>% 
  set("branches_k_col", k = 7, c("#3498DB",    # Blue
                                 "#2ECC71",    # Green
                                 "#F39C12",    # Gold/orange
                                 "#E74C3C",    # Red
                                 "#D979C9",    # Pink
                                 "#9B59B6",    # Purple
                                 #"#9F83D4",    # Grape
                                 "#1ABCB4")) #,    # Teal
                                 #"#34495E"))   # Slate blue

agnes_dend_clust_init_ggd <- agnes_dend_clust_init %>% 
  as.ggdend()
```

```{r agnes_init_cluster_characteristics, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 4}
ag_init_clusts_kbl <- cluster_pct(agnes_dend_clust_init_ggd)
ag_init_clust_labs <- cluster_labs(agnes_dend_clust_init_ggd)
```

```{r agnes_dend_clust_init, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.75, fig.height = 6.75}
# 7 clusters for AGNES
ggthemr("flat", spacing = 0.1)

agnes_dend_clust_init_gg <- ggplot(agnes_dend_clust_init_ggd, labels = FALSE) +
  geom_text(data = ag_init_clust_labs, aes(x = x_lab, y = -0.5, label = cluster_num, color = cluster_col)) +
  scale_y_reverse() +
  coord_polar(theta = "x") +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank()) +
  xlab("") +
  ylab("") #+
  #ggtitle("AGNES Dendrogram, k = 7 Clusters")
agnes_dend_clust_init_gg

ggthemr("flat")
```

```{r diana_dend_clust_ggd_init, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5}
# 6 clusters for DIANA
di_labcolors <- unsup_labs_reord_di %>% 
  as_tibble()

diana_dend_clust_init <- nhanes_diana %>% 
  as.dendrogram() %>% 
  set("leaves_pch", 20, col = di_labcolors$leafcolor) %>% 
  set("leaves_col", di_labcolors$leafcolor) %>% 
  set("branches_lwd", 0.5) %>% 
  set("branches_k_col", k = 6, c("#3498DB",    # Blue
                                 "#2ECC71",    # Green
                                 "#F39C12",    # Gold/orange
                                 "#E74C3C",    # Red
                                 "#D979C9",    # Pink
                                 "#9B59B6"))#,    # Purple
                                 #"#9F83D4",    # Grape
                                 #"#1ABCB4",    # Teal
                                 #"#34495E"))   # Slate blue

diana_dend_clust_init_ggd <- diana_dend_clust_init %>% 
  as.ggdend()
```

```{r diana_init_cluster_characteristics, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 10, fig.height = 4}
di_init_clusts_kbl <- cluster_pct(diana_dend_clust_init_ggd)
di_init_clust_labs <- cluster_labs(diana_dend_clust_init_ggd)
```

```{r diana_dend_clust_init, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.75, fig.height = 6.75}
diana_dend_clust_init_gg <- ggplot(diana_dend_clust_init_ggd, labels = FALSE) +
  geom_text(data = di_init_clust_labs, aes(x = x_lab, y = -0.15, label = cluster_num, color = cluster_col)) +
  scale_y_reverse() +
  coord_polar(theta = "x") +
  theme(axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank()) +
  xlab("") +
  ylab("") #+
  #ggtitle("DIANA Dendrogram, k = 6 Clusters")
diana_dend_clust_init_gg

ggthemr("flat")
```


<!-- CONTINUE HERE: -->
<!-- The below text needs to be updated after re-evaluation of these initial dendrogram plots. -->
<!-- At first glance it seems both plots were able to group obese and overweight pretty well for one cluster! -->












<!-- These dendrograms were re-run using $k = 6$ clusters for AGNES and $k = 9$ clusters for DIANA; output is shown below. -->

<!-- ```{r agnes_dend_clust_v2, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5} -->
<!-- # 6 clusters for AGNES -->
<!-- ggthemr("flat", spacing = 0.1) -->

<!-- agnes_dend_clust_v2 <- nhanes_agnes %>%  -->
<!--   as.dendrogram() %>%  -->
<!--   set("leaves_pch", 20, col = ag_labcolors$leafcolor) %>%  -->
<!--   set("leaves_col", ag_labcolors$leafcolor) %>%  -->
<!--   set("branches_lwd", 0.5) %>%  -->
<!--   set("branches_k_col", k = 6, c("#3498DB",    # Blue -->
<!--                                  "#2ECC71",    # Green -->
<!--                                  "#F39C12",    # Gold/orange -->
<!--                                  "#E74C3C",    # Red -->
<!--                                  #"#D979C9",    # Pink -->
<!--                                  "#9B59B6",    # Purple -->
<!--                                  #"#9F83D4",    # Grape -->
<!--                                  #"#1ABCB4",    # Teal -->
<!--                                  "#34495E"))   # Slate blue -->

<!-- agnes_dend_clust_v2_ggd <- agnes_dend_clust_v2 %>%  -->
<!--   as.ggdend() -->

<!-- agnes_dend_clust_v2_gg <- ggplot(agnes_dend_clust_v2_ggd, labels = FALSE) + -->
<!--   scale_y_reverse() + -->
<!--   coord_polar(theta = "x") + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text.x = element_blank(), -->
<!--         axis.text.y = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         panel.grid = element_blank()) + -->
<!--   xlab("") + -->
<!--   ylab("") #+ -->
<!--   #ggtitle("AGNES Dendrogram, k = 6 Clusters") -->
<!-- agnes_dend_clust_v2_gg -->

<!-- ggthemr("flat") -->
<!-- ``` -->

<!-- ```{r diana_dend_clust_v2, echo = FALSE, warning = FALSE, paged.print = FALSE, fig.width = 6.5, fig.height = 6.5} -->
<!-- # 9 clusters for DIANA -->
<!-- ggthemr("flat", spacing = 0.1) -->

<!-- diana_dend_clust_v2 <- nhanes_diana %>%  -->
<!--   as.dendrogram() %>%  -->
<!--   set("leaves_pch", 20, col = di_labcolors$leafcolor) %>%  -->
<!--   set("leaves_col", di_labcolors$leafcolor) %>%  -->
<!--   set("branches_lwd", 0.5) %>%  -->
<!--   set("branches_k_col", k = 9, c("#3498DB",    # Blue -->
<!--                                  "#2ECC71",    # Green -->
<!--                                  "#F39C12",    # Gold/orange -->
<!--                                  "#E74C3C",    # Red -->
<!--                                  "#D979C9",    # Pink -->
<!--                                  "#9B59B6",    # Purple -->
<!--                                  "#9F83D4",    # Grape -->
<!--                                  "#1ABCB4",    # Teal -->
<!--                                  "#34495E"))   # Slate blue -->

<!-- diana_dend_clust_v2_ggd <- diana_dend_clust_v2 %>%  -->
<!--   as.ggdend() -->

<!-- diana_dend_clust_v2_gg <- ggplot(diana_dend_clust_v2_ggd, labels = FALSE) + -->
<!--   scale_y_reverse() + -->
<!--   coord_polar(theta = "x") + -->
<!--   theme(axis.line = element_blank(), -->
<!--         axis.text.x = element_blank(), -->
<!--         axis.text.y = element_blank(), -->
<!--         axis.ticks = element_blank(), -->
<!--         panel.grid = element_blank()) + -->
<!--   xlab("") + -->
<!--   ylab("") #+ -->
<!--   #ggtitle("DIANA Dendrogram, k = 9 Clusters") -->
<!-- diana_dend_clust_v2_gg -->

<!-- ggthemr("flat") -->
<!-- ``` -->